DHT_PIN = 1
PRESENCE_PIN = 2
PRESENCE_TX_PIN = 3
PRESENSE_RX_PIN = 4
AIR_DIN_PIN = 5
AIR_ADC_PIN = 6

WIFI_SSID = "jimmy-XPS"
WIFI_PASSWORD = "akhbvkanv"

GRAPHQL_HOST = "localhost"
GRAPHQL_PORT = 5000
GRAPHQL_PATH = "/"