DHT_PIN = 26
PRESENCE_PIN = 35
#PRESENCE_TX_PIN = 3
#PRESENSE_RX_PIN = 4
#AIR_DIN_PIN = 5
AIR_ADC_PIN = 32

WIFI_SSID = "JimmyXPS"
WIFI_PASSWORD = "ashvbiqbrglncawuhciuwli"

GRAPHQL_HOST = "192.168.12.1"
GRAPHQL_PORT = 5000
GRAPHQL_PATH = "/"